### PR TITLE
Small name error at the start of the instructions.

### PR DESCRIPTION
**Pull request by JamesJansson**

### CODE REVIEW

**Comment by nuanprae** [comment]
Edit: Sorry, I'm new to gitHub. Just saw the files changed tab and it's the same one. 

Was it this one in Level 1 instruction? 
`var name = document.letterToSanta.myName.value;` 
It should be name instead of myName. Is that correct?

**Comment by JamesJansson** [comment]
That's correct, you should be able to accept the pull request if you are an admin to bring this change in.

**Comment by nuanprae** [comment]
Sorry, I'm not an admin. I was one of the people learning JS on Saturday.

**Comment by ButenkoT** [comment]
Thank you @JamesJansson ! Merging it in :)

**Pull request merged**
